title: 小琳的星空
# 左侧栏名字
author_name: 小琳

# 左侧栏标签，内容
user_tags:
 - '中二'
 - '乐天派'
 - '悲观主义'
#tag2: 悲观主义的乐天派

# 左侧栏Github连接
#github_url: https://github.com/Aizener
# 用户链接 icon, title, 链接
user_links:
 - ['xiao-lin-blog-github', 'github', 'https://github.com/']
 - ['xiao-lin-blog-gitee', '码云', 'https://gitee.com/xiao-lin']
 - ['xiao-lin-blog-csdn', 'CSDN', 'https://blog.csdn.net/weixin_43728193?type=blog']
 - ['xiao-lin-blog-cnblogs', '博客园', 'https://www.cnblogs.com/xiao-lin-unit/']

# 左侧栏座右铭，分两句
motto_prev: 跳出圈子你会发现
motto_last: 其实你一无是处

# 小站部署日期（运营时间）
public_date: 2023-11-22

# 左侧栏菜单
menu:
  - [小站首页, '/', 'icon-shouye']
  - [个人日志, '/log', 'icon-rizhi']
  - [友情链接, '/link', 'icon-youqinglianjie']
  - [关于自己, '/about', 'icon-guanyuwomen']
  - [标签, '/tags', 'xiao-lin-blog-tags-rectangle']
  - [分类, '/categories', 'xiao-lin-blog-categories']
#  - [我的工具, '/tools', 'icon-gongju']

# 友情连接：头像、名字、链接
links:
 - ['https://p1.ssl.qhmsg.com/t014f13b49e4fbc22dc.jpg', 'Hexo.', 'https://hexo.io/zh-cn/']
 - ['https://img95.699pic.com/photo/50042/4589.jpg_wh860.jpg', 'Hexo.', 'https://hexo.io/zh-cn/']

# 右侧栏公告
notice: 我们在绵延的海滩上捡贝壳，今天捡到了不必欣喜，因为海很大，今天没捡到，也不必失落，因为海很大。

# 右侧音乐列表：歌名、作者、链接、封面
musics:
 - ['自転车', 'オレスカバンド', '/music/自転车-オレスカバンド.mp3', 'imgs/music-bg1.jpg']
 - ['撞地球', '鱼儿七', '/music/撞地球-鱼儿七.mp3', 'imgs/music-bg1.jpg']
 - ['晴天', '周杰伦', '/music/晴天-周杰伦.mp3', 'imgs/music-bg1.jpg']
 - ['告白气球', '周杰伦', '/music/告白气球-周杰伦.mp3', 'imgs/music-bg1.jpg']

# 博客封面
cover:
  default: '/imgs/cover/default-cover.webp'
  list:
   - '/imgs/cover/default-cover.webp'
   - '/imgs/cover/default-cover.jpeg'

# 个人介绍
likes:
  - 姓名：小琳
  - 出生年月：96年3月
  - 性别：♂
  - QQ：2415171965
  - Email：xiao_lin_unit@163.com
  - 家乡：山东潍坊
  - 现居住地：江苏南京
  - 职业：JAVA开发
  - 爱好：音乐，动漫，电影，吃
  - 个人描述：空闲的时候喜欢心血来潮的搞点小东西，学点感兴趣的东西。休息无聊也会出去逛逛撸个串，像是一个悲观主义的乐天派，思想上思绪太多，行为上乐得自在。

# 工具配置：封面，标题，介绍，链接
tools:
  # - ['https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/30e94204580a4dbd83a64d4f91a9a6e5~tplv-k3u1fbpfcp-no-mark:240:240:240:160.awebp?', 'PNG图片压缩器', '这是一款无损压缩PNG图片的在线工具，可以童工上传或拖动来批量压缩图片并打包下载', 'http://1.14.43.39:5000/']
  - ['https://coke-cola.gitee.io/resume-page/assets/dark-f439b888.jpeg', '在线简历生成器', '一个免费的在线简历生成工具', 'https://coke-cola.gitee.io/resume-page/#/']

# 右侧栏网站信息
copyright: 我好像没有网络备案


# 是否开启文章评论 Valine:https://valine.js.org/configuration.htm
comments:
  enable: true
  appId: 'Pf8zCXGEH1qsprnWfikVVujL-gzGzoHsz'
  appKey: 'qOqoiUHhH1TGtLRUYURkLRQX'
  placeholder: '请留下你宝贵的意见吧~'
  meta: ['nick']
  recordIP: true
  visitor: true
  enableQQ: true

# 纪念模式 none: 不设置 all：全部置灰 index: 首页置灰
gray: none

# 日志篇幅超过1000字后隐藏（最大高度为1000px)，1000可为任意数值
log_text_num: 1000

# 版本号
version: 1.0.2
